trigger:
  branches:
    include:
      - main
      - feature/*

pool:
  vmImage: ubuntu-latest

variables:
  PROJECT_ID: 'fluted-factor-438905-d2'
  REGION: 'asia-south1'
  REPO_NAME: 'todo-repo'
  SERVICE_ACCOUNT: 'todo-deployer@fluted-factor-438905-d2.iam.gserviceaccount.com'
  CD_PIPELINE_NAME: 'azure-pipelines-cd.yml'  # Name of the CD pipeline file

stages:
# ---------- Stage 1: Build and Push ----------
- stage: Build
  displayName: Build and Push Docker Images
  jobs:
  - job: BuildAndPush
    displayName: Build & Push to Google Artifact Registry
    steps:
    - checkout: self

    # ✅ Fixed Authentication Step
    - task: Bash@3
      displayName: 'Authenticate to Google Artifact Registry'
      inputs:
        targetType: 'inline'
        script: |
          echo "$GCLOUD_SERVICE_KEY_B64" | base64 --decode > ${HOME}/gcloud-key.json
          echo "✅ Decoded service account key"
          gcloud auth activate-service-account $SERVICE_ACCOUNT --key-file=${HOME}/gcloud-key.json
          gcloud config set project $PROJECT_ID
          gcloud auth configure-docker $REGION-docker.pkg.dev --quiet
      env:
        GCLOUD_SERVICE_KEY_B64: $(GCLOUD_SERVICE_KEY_B64)
        PROJECT_ID: $(PROJECT_ID)
        REGION: $(REGION)
        SERVICE_ACCOUNT: $(SERVICE_ACCOUNT)

    - task: Bash@3
      displayName: Build Docker Images
      inputs:
        targetType: 'inline'
        script: |
          docker build -t frontend:$(Build.BuildId) ./frontend
          docker build -t backend:$(Build.BuildId) ./backend

    - task: Bash@3
      displayName: Push to Google Artifact Registry
      inputs:
        targetType: 'inline'
        script: |
          docker tag frontend:$(Build.BuildId) $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/frontend:$(Build.BuildId)
          docker tag backend:$(Build.BuildId) $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/backend:$(Build.BuildId)
          
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/frontend:$(Build.BuildId)
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/backend:$(Build.BuildId)

    - publish: k8s
      artifact: k8s-manifests
      displayName: Publish Kubernetes manifests as artifacts

# ---------- Stage 2: Trigger CD ----------
- stage: TriggerCD
  displayName: Trigger CD Pipeline
  dependsOn: Build
  jobs:
  - job: TriggerDeploy
    displayName: Trigger Continuous Deployment
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: 'k8s-manifests'
        path: '$(Pipeline.Workspace)/k8s'

    - task: Bash@3
      displayName: 'Trigger CD Pipeline'
      inputs:
        targetType: 'inline'
        script: |
          echo "Triggering CD pipeline for deployment..."
          echo "##vso[build.queueBuild]definitionName=ToDo-CD"
