trigger: none  # triggered by CI pipeline

pool:
  vmImage: ubuntu-latest

variables:
  PROJECT_ID: 'fluted-factor-438905-d2'
  REGION: 'asia-south1'
  REPO_NAME: 'todo-repo'
  CLUSTER_NAME: 'todo-cluster'
  CLUSTER_ZONE: 'asia-south1-a'
  SERVICE_ACCOUNT: 'todo-deployer@fluted-factor-438905-d2.iam.gserviceaccount.com'

stages:
- stage: Deploy
  displayName: Deploy to GKE
  jobs:
  - deployment: DeployToGKE
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: Bash@3
            displayName: Authenticate with Google Cloud
            inputs:
              targetType: 'inline'
              script: |
                echo "$GCLOUD_SERVICE_KEY" > key.json
                gcloud auth activate-service-account $SERVICE_ACCOUNT --key-file=key.json
                gcloud config set project $PROJECT_ID
                gcloud container clusters get-credentials $CLUSTER_NAME --zone $CLUSTER_ZONE --project $PROJECT_ID

          - task: Bash@3
            displayName: Deploy to GKE
            inputs:
              targetType: 'inline'
              script: |
                BUILD_ID=$(Build.BuildId)
                echo "Deploying images tagged with Build ID: $BUILD_ID"
                sed -i "s|IMAGE_FRONTEND|$REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/frontend:$BUILD_ID|g" k8s/frontend-deployment.yaml
                sed -i "s|IMAGE_BACKEND|$REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/backend:$BUILD_ID|g" k8s/backend-deployment.yaml

                kubectl apply -f k8s/
