CREATE DATABASE IF NOT EXISTS todo;
CREATE USER IF NOT EXISTS 'todo_user'@'%' IDENTIFIED BY 'todo_pass';
GRANT ALL PRIVILEGES ON todo.* TO 'todo_user'@'%';
FLUSH PRIVILEGES;
CREATE TABLE IF NOT EXISTS todo.tasks (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL
);
